baseURL = "https://scroix.github.io/"
publishDir = "docs"
languageCode = "en-us"
title = "ʕ•ᴥ•ʔ"
enableEmoji = true

[params]
    navigation = ["education", "work", "projects"]
    style = ""
    github = "https://github.com/scroix"
    gitlab = "https://gitlab.com/scroix"

[markup.goldmark.renderer]
    unsafe = true